<?php

class Point3D extends Point2D
{
public $z;
function __construct($x, $y,$z)
{
    parent::__construct($x, $y);
    $this->z = $z;
}

    /**
     * @return mixed
     */
    public function getZ()
    {
        return $this->z;
    }

    /**
     * @param mixed $z
     */
    public function setZ($z)
    {
        $this->z = $z;
    }
function getXYZ(){
        $arr1 = array(parent::getXY(),"z"=>$this->z);
return $arr1;
}
function  toString()
{
    return "x,y,z lan luot la: ". $this->getXYZ(); // TODO: Change the autogenerated stub
}
}