<?php

class Cylinder extends Circle
{
public $height;
function __construct($color, $radius,$height)
{
    parent::__construct($color, $radius);
    $this->height = $height;
}
    public function getArea()
    {
        return parent::getArea() * 2 + parent::getPerimeter() * $this->height;
    }

   public function calculateVolume()
    {
        return parent::getArea() * $this->height;
    }
    public function toString()
    {
        return parent::toString()." the tich: ".$this->calculateVolume(); // TODO: Change the autogenerated stub
    }
}